"""Add ImportJobs

Revision ID: 460b1e388ea2
Revises: aa7399e18a3d
Create Date: 2026-08-22 21:41:04.415057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460b1e388ea2'
down_revision: Union[str, Sequence[str], None] = 'aa7399e18a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='importjobstatus'), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_parsed', sa.Integer(), nullable=False),
    sa.Column('parse_failed', sa.Integer(), nullable=False),
    sa.Column('raw_records_stored', sa.Integer(), nullable=False),
    sa.Column('normalized', sa.Integer(), nullable=False),
    sa.Column('normalization_failed', sa.Integer(), nullable=False),
    sa.Column('unsupported', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_tenant_id'), 'import_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_tenant_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
