"""Add PERSISTENCE_FAILED

Revision ID: 61a8524a4133
Revises: 6a4f285c1b55
Create Date: 2026-08-22 02:32:23.844040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a8524a4133'
down_revision: Union[str, Sequence[str], None] = '6a4f285c1b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE processingstatus ADD VALUE IF NOT EXISTS 'PERSISTENCE_FAILED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
