"""Initial Phase 3 schema

Revision ID: 6a4f285c1b55
Revises: 
Create Date: 2026-08-22 02:24:15.309823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4f285c1b55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_vendor', sa.String(), nullable=False),
    sa.Column('source_product', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'NORMALIZED', 'NORMALIZATION_FAILED', name='processingstatus'), nullable=False),
    sa.Column('normalization_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_tenant_id'), 'raw_events', ['tenant_id'], unique=False)
    op.create_table('normalized_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_event_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_vendor', sa.String(), nullable=False),
    sa.Column('source_product', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('command_line', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('file_hash_algorithm', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_alerts_tenant_id'), 'normalized_alerts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_alerts_tenant_id'), table_name='normalized_alerts')
    op.drop_table('normalized_alerts')
    op.drop_index(op.f('ix_raw_events_tenant_id'), table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###
