"""add_raw_payload_sha256

Revision ID: 7a7d31db62a3
Revises: a1926b23619b
Create Date: 2026-08-22 22:35:01.207018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7d31db62a3'
down_revision: Union[str, Sequence[str], None] = 'a1926b23619b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_events', sa.Column('raw_payload_sha256', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_events', 'raw_payload_sha256')
    # ### end Alembic commands ###
