"""add_storage_tier

Revision ID: a1926b23619b
Revises: 460b1e388ea2
Create Date: 2026-08-22 22:29:20.242140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1926b23619b'
down_revision: Union[str, Sequence[str], None] = '460b1e388ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    storage_tier_enum = sa.Enum('HOT_POSTGRES', 'COLD_OBJECT_STORE', 'ARCHIVED', name='storagetier')
    storage_tier_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('raw_events', sa.Column('storage_tier', storage_tier_enum, nullable=False, server_default='HOT_POSTGRES'))
    op.add_column('raw_events', sa.Column('external_storage_pointer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_events', 'external_storage_pointer')
    op.drop_column('raw_events', 'storage_tier')
    # ### end Alembic commands ###
