"""phase_4_models

Revision ID: a549cf7bc412
Revises: 61a8524a4133
Create Date: 2026-08-22 03:59:29.993930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a549cf7bc412'
down_revision: Union[str, Sequence[str], None] = '61a8524a4133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('aggregation_key', sa.String(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_signals_tenant_id'), 'aggregated_signals', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('incident_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('anchor_entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_rule_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'incident_key', name='uq_tenant_incident_key')
    )
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('correlation_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('left_signal_id', sa.Uuid(), nullable=False),
    sa.Column('right_signal_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['left_signal_id'], ['aggregated_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_signal_id'], ['aggregated_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_signal_id', 'right_signal_id', 'rule_version', name='uq_corr_edge')
    )
    op.create_index(op.f('ix_correlation_edges_tenant_id'), 'correlation_edges', ['tenant_id'], unique=False)
    op.create_table('incident_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('aggregated_signal_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_signal_id'], ['aggregated_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'aggregated_signal_id', name='uq_incident_signal')
    )
    op.create_table('aggregated_signal_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aggregated_signal_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_alert_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_signal_id'], ['aggregated_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['normalized_alert_id'], ['normalized_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aggregated_signal_id', 'normalized_alert_id', name='uq_agg_signal_alert')
    )
    with op.batch_alter_table('normalized_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_alert_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('dedup_fingerprint', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dedup_fingerprint_version', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_normalized_alerts_dedup_fingerprint'), ['dedup_fingerprint'], unique=False)
        batch_op.create_foreign_key('fk_norm_alerts_dup', 'normalized_alerts', ['duplicate_of_alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_norm_alerts_dup', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_normalized_alerts_dedup_fingerprint'))
        batch_op.drop_column('dedup_fingerprint_version')
        batch_op.drop_column('dedup_fingerprint')
        batch_op.drop_column('duplicate_of_alert_id')
    op.drop_table('aggregated_signal_alerts')
    op.drop_table('incident_signals')
    op.drop_index(op.f('ix_correlation_edges_tenant_id'), table_name='correlation_edges')
    op.drop_table('correlation_edges')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_aggregated_signals_tenant_id'), table_name='aggregated_signals')
    op.drop_table('aggregated_signals')
    # ### end Alembic commands ###
