"""brain1_hardening

Revision ID: d00f5a9ff1f7
Revises: fef8b4623a22
Create Date: 2026-08-22 09:55:16.074133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00f5a9ff1f7'
down_revision: Union[str, Sequence[str], None] = 'fef8b4623a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain1_processing_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('last_processed_ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_processed_alert_id', sa.String(), nullable=False),
    sa.Column('correlation_rule_version', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain1_processing_state_tenant_id'), 'brain1_processing_state', ['tenant_id'], unique=True)
    op.create_table('signal_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('aggregated_signal_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_value', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_signal_id'], ['aggregated_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'aggregated_signal_id', 'entity_type', 'entity_value', name='uq_signal_entity')
    )
    op.create_index(op.f('ix_signal_entities_tenant_id'), 'signal_entities', ['tenant_id'], unique=False)
    op.add_column('aggregated_signals', sa.Column('aggregation_rule_id', sa.String(), nullable=False))
    op.add_column('aggregated_signals', sa.Column('creation_anchor_alert_id', sa.String(), nullable=False))
    op.add_column('incidents', sa.Column('incident_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'incident_type')
    op.drop_column('aggregated_signals', 'creation_anchor_alert_id')
    op.drop_column('aggregated_signals', 'aggregation_rule_id')
    op.drop_index(op.f('ix_signal_entities_tenant_id'), table_name='signal_entities')
    op.drop_table('signal_entities')
    op.drop_index(op.f('ix_brain1_processing_state_tenant_id'), table_name='brain1_processing_state')
    op.drop_table('brain1_processing_state')
    # ### end Alembic commands ###
