"""Add composite index for candidate retrieval

Revision ID: ed4fadaac8ca
Revises: d00f5a9ff1f7
Create Date: 2026-08-22 11:08:09.456770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4fadaac8ca'
down_revision: Union[str, Sequence[str], None] = 'd00f5a9ff1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_signal_entities_lookup', 'signal_entities', ['tenant_id', 'entity_type', 'entity_value', 'last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signal_entities_lookup', table_name='signal_entities')
    # ### end Alembic commands ###
