"""Add brain 2 models

Revision ID: f972433327d0
Revises: ed4fadaac8ca
Create Date: 2026-08-22 11:25:34.171218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f972433327d0'
down_revision: Union[str, Sequence[str], None] = 'ed4fadaac8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain2_investigation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('incident_version', sa.Integer(), nullable=False),
    sa.Column('safe_package_fingerprint', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'STALE', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain2_investigation_jobs_tenant_id'), 'brain2_investigation_jobs', ['tenant_id'], unique=False)
    op.create_table('brain2_investigation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('brain2_policy_version', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED_VALIDATION', 'FAILED_TIMEOUT', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['brain2_investigation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain2_investigation_runs_tenant_id'), 'brain2_investigation_runs', ['tenant_id'], unique=False)
    op.create_table('brain2_investigation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('primary_hypothesis', sa.String(), nullable=False),
    sa.Column('supporting_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contradicting_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recommended_disposition', sa.String(), nullable=False),
    sa.Column('recommended_priority', sa.String(), nullable=False),
    sa.Column('next_best_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attack_hypotheses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('limitations', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['brain2_investigation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_brain2_investigation_results_tenant_id'), 'brain2_investigation_results', ['tenant_id'], unique=False)
    op.add_column('incidents', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'version')
    op.drop_index(op.f('ix_brain2_investigation_results_tenant_id'), table_name='brain2_investigation_results')
    op.drop_table('brain2_investigation_results')
    op.drop_index(op.f('ix_brain2_investigation_runs_tenant_id'), table_name='brain2_investigation_runs')
    op.drop_table('brain2_investigation_runs')
    op.drop_index(op.f('ix_brain2_investigation_jobs_tenant_id'), table_name='brain2_investigation_jobs')
    op.drop_table('brain2_investigation_jobs')
    # ### end Alembic commands ###
