"""add_entities_to_aggregated_signals

Revision ID: fef8b4623a22
Revises: a549cf7bc412
Create Date: 2026-08-22 04:26:02.601362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fef8b4623a22'
down_revision: Union[str, Sequence[str], None] = 'a549cf7bc412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregated_signals', sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aggregated_signals', 'entities')
    # ### end Alembic commands ###
